name: hive_collection
description: A lightweight Hive-based collection library for Dart and Flutter.
version: 1.0.4
repository: https://github.com/Glitch9Inc/hive_collection
homepage: https://github.com/Glitch9Inc/hive_collection

environment:
  sdk: ^3.6.2
 
dependencies:
  # hive: ^4.0.0-dev.2
  # isar: ^4.0.0-dev.14
  # isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.0.11  

  # migrating to hive-ce
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
